name: "GitHub Workflow for Pull Requests"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install deps
        run: make install

      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install deps
        run: make install

      - name: Lint
        run: make lint

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install deps
        run: make install

      - name: Format
        run: make fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Committing format changes from workflow (make fmt)"


  testPublish:
    runs-on: ubuntu-latest
    needs: [fmt, lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # - name: Install pipenv
      #   run: pip install pipenv

      - name: Test building a release will work
        run: |
          rm -rf dist
          pipenv run python3 setup.py sdist
          pipenv run pip install dist/*.tar.gz
          pipenv run floop

      - name: Test publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/